# -*- coding: utf-8 -*-
"""Adrice Network form credentials per HappyFam offer id."""
UID = "019e548b-7f4c-705c-b841-a66cbf5933fa"
WEBHOOK = "https://hook.eu2.make.com/utxqa26bkppfdcziwfwh6xfdni67agrc"
ACTION = "https://offers.adricenetwork.com/forms/html/"
SCRIPT = "https://offers.adricenetwork.com/forms/html/js-v2/"

FORMS = {
    "2409": {
        "lp": "2434",
        "key": "08ce0373690ab72ac0e52ef90fafbbfe9b234616",
        "label_name": "Keresztnév Vezetéknév*",
        "ph_name": "Keresztnév Vezetéknév",
        "label_address": "Cím*",
        "ph_address": "Cím",
        "label_tel": "Telefon*",
        "ph_tel": "Telefon",
        "field_order": ("name", "address", "tel"),
        "submit": "Rendeljen most",
    },
    "3176": {
        "lp": "3210",
        "key": "b59ce5b160f3d2baf9c85b55ec209927713427f6",
        "label_name": "Nombre Apellido*",
        "ph_name": "Nombre Apellido",
        "label_address": "Dirección*",
        "ph_address": "Dirección",
        "label_tel": "Teléfono*",
        "ph_tel": "Teléfono",
        "field_order": ("name", "address", "tel"),
        "submit": "Haz tu pedido",
    },
    "3177": {
        "lp": "3211",
        "key": "2a7acbd02ee58de419bb05adcba282de8334053d",
        "label_name": "Vorname Nachname*",
        "ph_name": "Vorname Nachname",
        "label_address": "Anschrift*",
        "ph_address": "Anschrift",
        "label_tel": "Telefon*",
        "ph_tel": "Telefon",
        "field_order": ("name", "address", "tel"),
        "submit": "Jetzt bestellen",
    },
    "3178": {
        "lp": "3212",
        "key": "6c5ef7001bec9d02c864d2dd027ec98768a5e692",
        "label_name": "Vardas Pavardė*",
        "ph_name": "Vardas Pavardė",
        "label_address": "Adresas*",
        "ph_address": "Adresas",
        "label_tel": "Telefonas*",
        "ph_tel": "Telefonas",
        "field_order": ("name", "address", "tel"),
        "submit": "Užsisakykite dabar",
    },
    "3179": {
        "lp": "3213",
        "key": "8189236fb70974f62d524f74ac8004806b7ee5cc",
        "label_name": "Imię Nazwisko*",
        "ph_name": "Imię Nazwisko",
        "label_address": "Adres*",
        "ph_address": "Adres",
        "label_tel": "Telefon*",
        "ph_tel": "Telefon",
        "field_order": ("name", "address", "tel"),
        "submit": "Zamów teraz",
    },
    "3251": {
        "lp": "3285",
        "key": "2a53aed12ba7f92968374f1928af094d2d0bf10b",
        "label_name": "Jméno Příjmení*",
        "ph_name": "Jméno Příjmení",
        "label_address": "Adresa*",
        "ph_address": "Adresa",
        "label_tel": "Telefon*",
        "ph_tel": "Telefon",
        "field_order": ("name", "address", "tel"),
        "submit": "Objednat nyní",
    },
    "3702": {
        "lp": "3742",
        "key": "a92acf86ab920e4d23f9065e28eb20b2acd34c49",
        "label_name": "Meno Priezvisko*",
        "ph_name": "Meno Priezvisko",
        "label_address": "Adresa*",
        "ph_address": "Adresa",
        "label_tel": "Telefón*",
        "ph_tel": "Telefón",
        "field_order": ("name", "address", "tel"),
        "submit": "Objednajte si teraz",
    },
    "4095": {
        "lp": "4135",
        "key": "c6faa0732b0f2941196d6b45fc036b3b746668df",
        "label_name": "Vārds Uzvārds*",
        "ph_name": "Vārds Uzvārds",
        "label_address": "Adrese*",
        "ph_address": "Adrese",
        "label_tel": "Tālrunis*",
        "ph_tel": "Tālrunis",
        "field_order": ("name", "address", "tel"),
        "submit": "Pasūtiet tagad",
    },
    "1476": {
        "lp": "1496",
        "key": "01fd07b5550a42fcb1e5e02062e81bec1358495f",
        "label_name": "Nome e sobrenome*",
        "ph_name": "Nome e sobrenome",
        "label_address": "Endereço*",
        "ph_address": "Endereço",
        "label_tel": "Telefone*",
        "ph_tel": "Telefone",
        "field_order": ("name", "tel", "address"),
        "submit": "Enviar o pedido",
    },
}

CPA = {
    "2409": 18.0,
    "3176": 17.0,
    "3177": 22.0,
    "3178": 17.0,
    "3179": 19.0,
    "3251": 15.0,
    "3702": 16.0,
    "4095": 19.0,
    "1476": 16.0,
}
